services:
  web-nginx:
    image: inchange/web-nginx:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.http.routers.web-nginx-https.tls=true
        - traefik.http.routers.web-nginx-https.tls.certresolver=cloudflare
        - traefik.http.routers.web-nginx-https.rule=Host(`inchange.dev`)
        - traefik.http.routers.web-nginx-https.entrypoints=websecure
        - traefik.http.services.web-nginx.loadbalancer.server.port=80
      replicas: 1
      # resources:
      # limits:
      #   cpus: "1"
      #   memory: 512M
      # reservations:
      #   cpus: "0.25"
      #   memory: 128M
      # placement:
      #   constraints:
      #     - node.role == worker
      restart_policy:
        condition: any
        delay: 2s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 3s
        order: start-first

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true
