name: Build Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "GITHUB_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        env:
          TAG: sha-${{ env.GITHUB_SHORT_SHA }}
        run: |
          docker build -f docker/Dockerfile -t inchange/web-nginx:${TAG} .
          docker save inchange/web-nginx:${TAG} -o web-nginx.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-nginx
          path: web-nginx.tar
          retention-days: 1
