name: Deploy Application

on:
  workflow_call:
    secrets:
      SSH_USERNAME:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      EMAIL:
        required: true
      CF_DNS_API_TOKEN:
        required: true

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: web-nginx
          path: .

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_rsa
          chmod 600 ~/.ssh/deploy_rsa

          cat >> ~/.ssh/config <<END
          Host deploy
            HostName ${{ vars.SSH_HOST }}
            Port ${{ vars.SSH_PORT }}
            User ${{ secrets.SSH_USERNAME }}
            IdentityFile ~/.ssh/deploy_rsa
            StrictHostKeyChecking no
          END

      - name: Create remote Docker context
        run: |
          docker context create remote --docker "host=ssh://deploy"
          docker context use remote

      - name: Deploy compose
        run: |
          docker load -i "web-nginx.tar"

          docker stack deploy -c docker/stack.yml web-nginx
